# Generated by Django 5.2.7 on 2025-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_ordering_to_course_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
