# Generated by Django 5.2.7 on 2025-12-21 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_add_ordering_to_gamification_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_award', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('once', 'Once')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-points_award', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='gamification.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_date'],
                'unique_together': {('user', 'challenge', 'completed_date')},
            },
        ),
    ]
