# Generated by Django 5.2.7 on 2025-12-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_add_points_per_question_to_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-is_correct', 'text']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_type', 'text']},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at', 'title']},
        ),

    ]
