# Generated by Django 5.2.7 on 2025-12-21 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_add_ordering_to_quiz_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='mcq_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='quiz.quizsubmission')),
            ],
            options={
                'ordering': ['question__question_type', 'question__text'],
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
