# Generated by Django 5.2.7 on 2025-12-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagereaction_message_edited_at_message_mentions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at']},
        ),
    ]
